/*
Generated by UnityTwine on 5/2/2016 7:32:14 AM
https://github.com/daterre/UnityTwine
*/
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityTwine;

public class Story: TwineStory
{
	public TwineVar sociability;
	public TwineVar suspicion;
	public TwineVar fail;
	public TwineVar morals;
	public TwineVar metFriend;
	public override TwineVar this[string name] {
		get {
			switch(name)
			{
				case "sociability": return sociability;
				case "suspicion": return suspicion;
				case "fail": return fail;
				case "morals": return morals;
				case "metFriend": return metFriend;
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
		set {
			switch(name) {
				case "sociability": sociability = value; break;
				case "suspicion": suspicion = value; break;
				case "fail": fail = value; break;
				case "morals": morals = value; break;
				case "metFriend": metFriend = value; break;
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
	}


	void Awake() {
		base.Init();
		passageInit_0();
		passageInit_1();
		passageInit_2();
		passageInit_3();
		passageInit_4();
		passageInit_5();
		passageInit_6();
		passageInit_7();
		passageInit_8();
		passageInit_9();
		passageInit_10();
		passageInit_11();
		passageInit_12();
		passageInit_13();
		passageInit_14();
		passageInit_15();
		passageInit_16();
		passageInit_17();
		passageInit_18();
		passageInit_19();
		passageInit_20();
		passageInit_21();
		passageInit_22();
		passageInit_23();
		passageInit_24();
		passageInit_25();
		passageInit_26();
		passageInit_27();
		passageInit_28();
		passageInit_29();
		passageInit_30();
		passageInit_31();
		passageInit_32();
		passageInit_33();
		passageInit_34();
		passageInit_35();
		passageInit_36();
		passageInit_37();
		passageInit_38();
		passageInit_39();
		passageInit_40();
		passageInit_41();
		passageInit_42();
		passageInit_43();
		passageInit_44();
		passageInit_45();
		passageInit_46();
		passageInit_47();
		passageInit_48();
		passageInit_49();
		passageInit_50();
		passageInit_51();
		passageInit_52();
		passageInit_53();
		passageInit_54();
		passageInit_55();
		passageInit_56();
		passageInit_57();
		passageInit_58();
		passageInit_59();
		passageInit_60();
		passageInit_61();
		passageInit_62();
		passageInit_63();
		passageInit_64();
		passageInit_65();
		passageInit_66();
		passageInit_67();
	}
    
	// .............
	// #0: StoryTitle

	void passageInit_0()
	{
		this.Passages["StoryTitle"] = new TwinePassage("StoryTitle", new string[]{  }, passageExecute_0);
	}

	IEnumerable<TwineOutput> passageExecute_0()
	{
		yield return new TwineText(@"New Science");	
	}
    
	// .............
	// #1: Beginning

	void passageInit_1()
	{
		this.Passages["Beginning"] = new TwinePassage("Beginning", new string[]{  }, passageExecute_1);
	}

	IEnumerable<TwineOutput> passageExecute_1()
	{
		yield return new TwineText(@"Recently, Aya's pet Oyo died of an illness. She is still sad, but life goes on.//A while later, she feels a bit better, but still shows up (drunk?) in her lab in the middle of the night. She decided to do experiments on Oyo because she feels like it's the right thing to do to make him still important to her, even after his death.//There was an old project she was working on a long time ago, but which she completely abandoned. She gets its data back, and continues a bit, but on Oyo.//At some point she notices that holy shit she's about to get some results. ");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Question", @"Question", @"Question", null, null);
		yield return new TwineText(@"");
		sociability = 0;
		suspicion = 0;
		fail = 0;
		morals = 0;
		metFriend = 0;	
	}
    
	// .............
	// #2: 10V

	void passageInit_2()
	{
		this.Passages["10V"] = new TwinePassage("10V", new string[]{  }, passageExecute_2);
	}

	IEnumerable<TwineOutput> passageExecute_2()
	{
		yield return new TwineText(@"Breakthrough! Oyo starts moving. Soon, he's back to life, but completely disoriented. Aya hurriedly grabs some water and food (there's always some in her lab for when she sneaks him in) and gives him.//Aya thinks about it : all the implications of it, the possible uses, how ""HOLY SHIT I FOUND THAT WHAT DO I DO""//Her best friend calls her to ask for news, she has to choose whether she tells her or not.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Think about it on her own", @"Think about it on her own", @"Think about it on her own", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"Ask her best friend for help", @"Ask her best friend for help", @"Ask her best friend for help", null, null);	
	}
    
	// .............
	// #3: Think about it on her own

	void passageInit_3()
	{
		this.Passages["Think about it on her own"] = new TwinePassage("Think about it on her own", new string[]{  }, passageExecute_3);
	}

	IEnumerable<TwineOutput> passageExecute_3()
	{
		sociability = sociability - 1;
		yield return new TwineText(@"");
		yield return new TwineText(@"She thinks it's a bad idea to share it with anyone for now, so she doesn't say anything and gives an excuse to not go out that evening. She goes home and sets up Oyo comfortably.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Day two", @"Day two", @"Day two", null, null);	
	}
    
	// .............
	// #4: Ask her best friend for help

	void passageInit_4()
	{
		this.Passages["Ask her best friend for help"] = new TwinePassage("Ask her best friend for help", new string[]{  }, passageExecute_4);
	}

	IEnumerable<TwineOutput> passageExecute_4()
	{
		sociability = sociability + 1;
		yield return new TwineText(@"");
		yield return new TwineText(@"She says she found something huge, and she doesn't know what to do and oh my god everything is overwhelming right now. Best friend calms her down, invites her to eat somewhere, and they spend the evening talking about it.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Day two", @"Day two", @"Day two", null, null);	
	}
    
	// .............
	// #5: Day two

	void passageInit_5()
	{
		this.Passages["Day two"] = new TwinePassage("Day two", new string[]{  }, passageExecute_5);
	}

	IEnumerable<TwineOutput> passageExecute_5()
	{
		yield return new TwineText(@"Aya has to make sure that what she did actually works and wasn't just a coincidence. It means more tests on dead things, and in particular, she will have to test it on a human body at some point.");
		yield return new TwineText(@"");
		if (sociability > 0) { 
		yield return new TwineLink(@"Do the thing with friend", @"Do the thing with friend", @"Do the thing with friend", null, null);} 
		if (sociability <= 0) { 
		yield return new TwineLink(@"Do the thing alone", @"Do the thing alone", @"Do the thing alone", null, null);
		} 	
	}
    
	// .............
	// #6: Do the thing with friend

	void passageInit_6()
	{
		this.Passages["Do the thing with friend"] = new TwinePassage("Do the thing with friend", new string[]{  }, passageExecute_6);
	}

	IEnumerable<TwineOutput> passageExecute_6()
	{
		sociability = sociability + 1;
		suspicion = suspicion + 1;
		metFriend = 1;
		yield return new TwineText(@"");
		yield return new TwineText(@"She decides that she should ask her friend for help in order to do the testing so she can confirm she's not crazy. She calls her, and she comes over.//Science happens.//They do tests on rats, no problem, they do tests on chimpanzees, they have to fix the dosage but eventually it works.//At some point boss shows up. They have to explain what they're doing.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Tell it's for a personal project.", @"Tell it's for a personal project.", @"Tell it's for a personal project.", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"Try to find an excuse.", @"Try to find an excuse.", @"Try to find an excuse.", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"Let friend handle.", @"Let friend handle.", @"Let friend handle.", null, null);	
	}
    
	// .............
	// #7: Do the thing alone

	void passageInit_7()
	{
		this.Passages["Do the thing alone"] = new TwinePassage("Do the thing alone", new string[]{  }, passageExecute_7);
	}

	IEnumerable<TwineOutput> passageExecute_7()
	{
		metFriend = -1;
		yield return new TwineText(@"");
		yield return new TwineText(@"She decides that it would be better if she did the testing alone because it's a pretty dark thing to do.//She tests on other small animals first to make sure that it works, which it does.//She then asks for one chimpanzee, and see that the dosage isn't strong enough. At some point, boss shows up, but she's so stressed about staying hidden that she manages to hide the body before he enters the room and she pretends to work on whatever it is she's supposed to be working on.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Go to next step", @"Go to next step", @"Go to next step", null, null);	
	}
    
	// .............
	// #8: 1V

	void passageInit_8()
	{
		this.Passages["1V"] = new TwinePassage("1V", new string[]{  }, passageExecute_8);
	}

	IEnumerable<TwineOutput> passageExecute_8()
	{
		fail = fail + 1;
		yield return new TwineText(@"");
		yield return new TwineText(@"She tries that, but nothing happens.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Question", @"Question", @"Question", null, null);	
	}
    
	// .............
	// #9: 100V

	void passageInit_9()
	{
		this.Passages["100V"] = new TwinePassage("100V", new string[]{  }, passageExecute_9);
	}

	IEnumerable<TwineOutput> passageExecute_9()
	{
		fail = fail + 1;
		yield return new TwineText(@"");
		yield return new TwineText(@"She gets a flashback from one fateful class back when she was in college where her lab partner fried a mouse, and she decides that she should definitely not do that.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Question", @"Question", @"Question", null, null);	
	}
    
	// .............
	// #10: Question

	void passageInit_10()
	{
		this.Passages["Question"] = new TwinePassage("Question", new string[]{  }, passageExecute_10);
	}

	IEnumerable<TwineOutput> passageExecute_10()
	{
		yield return new TwineText(@"Currently, he was injected with a solution she had worked on, now she has to apply current to him.//She should make sure that it's sufficient to be working, but not too much so she doesn't fry him.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"1V", @"1V", @"1V", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"10V", @"10V", @"10V", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"100V", @"100V", @"100V", null, null);	
	}
    
	// .............
	// #11: Go to next step

	void passageInit_11()
	{
		this.Passages["Go to next step"] = new TwinePassage("Go to next step", new string[]{  }, passageExecute_11);
	}

	IEnumerable<TwineOutput> passageExecute_11()
	{
		yield return new TwineText(@"Now she has to find a human body, which is way harder to get than just ask another lab for a spare chimpanzee. She asks around, and learns that she has to wait for the body of a new donor to come to the lab.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Ask around", @"Ask around", @"Ask around", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"Sneak in the dead storage", @"Sneak in the dead storage", @"Sneak in the dead storage", null, null);	
	}
    
	// .............
	// #12: Sneak in the dead storage

	void passageInit_12()
	{
		this.Passages["Sneak in the dead storage"] = new TwinePassage("Sneak in the dead storage", new string[]{  }, passageExecute_12);
	}

	IEnumerable<TwineOutput> passageExecute_12()
	{
		morals = morals - 1;
		sociability = sociability - 1;
		yield return new TwineText(@"");
		yield return new TwineText(@"She does that in the middle of the night.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Test on human", @"Test on human", @"Test on human", null, null);	
	}
    
	// .............
	// #13: Ask around

	void passageInit_13()
	{
		this.Passages["Ask around"] = new TwinePassage("Ask around", new string[]{  }, passageExecute_13);
	}

	IEnumerable<TwineOutput> passageExecute_13()
	{
		sociability = sociability + 1;
		suspicion = suspicion + 1;
		morals = morals + 1;
		yield return new TwineText(@"");
		if (sociability > 0) { yield return new TwineText(@"She asks around the lab, and she does that with enough skill so it works and she manages to meet a teacher who lets her have a body. She just has to do that in the evening, after classes.");
		yield return new TwineLink(@"Test on human", @"Test on human", @"Test on human", null, null);} 
		if (sociability <= 0) { yield return new TwineText(@"She asks around, but no one really know or want to let her have a body, so she has to do that by herself.");
		yield return new TwineLink(@"Sneak in the dead storage", @"Sneak in the dead storage", @"Sneak in the dead storage", null, null);} 	
	}
    
	// .............
	// #14: Test on human

	void passageInit_14()
	{
		this.Passages["Test on human"] = new TwinePassage("Test on human", new string[]{  }, passageExecute_14);
	}

	IEnumerable<TwineOutput> passageExecute_14()
	{
		yield return new TwineText(@"She does her test on a human body, finally.//However, the question is : what dosage?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Same as for chimpanzee", @"Same as for chimpanzee", @"Same as for chimpanzee", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"Less than chimpanzee", @"Less than chimpanzee", @"Less than chimpanzee", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"More than chimpanzee", @"More than chimpanzee", @"More than chimpanzee", null, null);	
	}
    
	// .............
	// #15: Same as for chimpanzee

	void passageInit_15()
	{
		this.Passages["Same as for chimpanzee"] = new TwinePassage("Same as for chimpanzee", new string[]{  }, passageExecute_15);
	}

	IEnumerable<TwineOutput> passageExecute_15()
	{
		fail = fail + 1;
		yield return new TwineText(@"");
		yield return new TwineText(@"The body jerks a bit, but nothing happens.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Test on human", @"Test on human", @"Test on human", null, null);	
	}
    
	// .............
	// #16: Less than chimpanzee

	void passageInit_16()
	{
		this.Passages["Less than chimpanzee"] = new TwinePassage("Less than chimpanzee", new string[]{  }, passageExecute_16);
	}

	IEnumerable<TwineOutput> passageExecute_16()
	{
		fail = fail + 1;
		yield return new TwineText(@"");
		yield return new TwineText(@"Nothing happens.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Test on human", @"Test on human", @"Test on human", null, null);	
	}
    
	// .............
	// #17: More than chimpanzee

	void passageInit_17()
	{
		this.Passages["More than chimpanzee"] = new TwinePassage("More than chimpanzee", new string[]{  }, passageExecute_17);
	}

	IEnumerable<TwineOutput> passageExecute_17()
	{
		yield return new TwineText(@"Victory! The person comes back to life.//They look a bit sick and disoriented, but alive. They have no idea what happened from the moment of their death.//Now she has to do something with that person. Especially since he's starting to ask questions.");
		if (fail > 3) { 
		yield return new TwineLink(@"End: Something's wrong", @"End: Something's wrong", @"End: Something's wrong", null, null);} 
		if (fail <= 3) { 
		yield return new TwineLink(@"Explain the situation", @"Explain the situation", @"Explain the situation", null, null);
		yield return new TwineLink(@"Lie", @"Lie", @"Lie", null, null);
		yield return new TwineLink(@"Knock him out", @"Knock him out", @"Knock him out", null, null);
		} 	
	}
    
	// .............
	// #18: End: Something's wrong

	void passageInit_18()
	{
		this.Passages["End: Something's wrong"] = new TwinePassage("End: Something's wrong", new string[]{  }, passageExecute_18);
	}

	IEnumerable<TwineOutput> passageExecute_18()
	{
		yield return new TwineText(@"Because you're not that good at what you're doing, the guy you reanimated just died.//Game over.");	
	}
    
	// .............
	// #19: Tell it's for a personal project.

	void passageInit_19()
	{
		this.Passages["Tell it's for a personal project."] = new TwinePassage("Tell it's for a personal project.", new string[]{  }, passageExecute_19);
	}

	IEnumerable<TwineOutput> passageExecute_19()
	{
		morals = morals + 1;
		yield return new TwineText(@"Boss says you shouldn't be working on personal things during work time and just leaves you there.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Go to next step", @"Go to next step", @"Go to next step", null, null);	
	}
    
	// .............
	// #20: Try to find an excuse.

	void passageInit_20()
	{
		this.Passages["Try to find an excuse."] = new TwinePassage("Try to find an excuse.", new string[]{  }, passageExecute_20);
	}

	IEnumerable<TwineOutput> passageExecute_20()
	{
		suspicion = suspicion + 1;
		morals = morals - 1;
		yield return new TwineText(@"You try to find an excuse but you're pretty incoherent. Boss is annoyed and just leaves after urging you to go back to your actual work.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Go to next step", @"Go to next step", @"Go to next step", null, null);	
	}
    
	// .............
	// #21: Let friend handle.

	void passageInit_21()
	{
		this.Passages["Let friend handle."] = new TwinePassage("Let friend handle.", new string[]{  }, passageExecute_21);
	}

	IEnumerable<TwineOutput> passageExecute_21()
	{
		suspicion = suspicion - 1;
		yield return new TwineText(@"You look expectantly at your friend, who explains that another scientist asked you to keep these animals for a while because of security concern, and launches into a whole monologue about putting security first. That seems to work, but you are still urged to go back to work.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Go to next step", @"Go to next step", @"Go to next step", null, null);	
	}
    
	// .............
	// #22: Explain the situation

	void passageInit_22()
	{
		this.Passages["Explain the situation"] = new TwinePassage("Explain the situation", new string[]{  }, passageExecute_22);
	}

	IEnumerable<TwineOutput> passageExecute_22()
	{
		yield return new TwineText(@"Aya tries explaining the situation to the guy. He has trouble believing it.");
		if (sociability > 0) { yield return new TwineText(@"But she's convincing enough that he believes her.");
		yield return new TwineLink(@"More talking", @"More talking", @"More talking", null, null);} 
		if (sociability <= 0) { 
		yield return new TwineLink(@"The man is freaking out", @"The man is freaking out", @"The man is freaking out", null, null);} 
		yield return new TwineText(@"");
		sociability = sociability + 1;
		morals = morals + 1;	
	}
    
	// .............
	// #23: Lie

	void passageInit_23()
	{
		this.Passages["Lie"] = new TwinePassage("Lie", new string[]{  }, passageExecute_23);
	}

	IEnumerable<TwineOutput> passageExecute_23()
	{
		yield return new TwineText(@"Aya decides to lie about the situation, telling the man that there was an error of diagnostic and that he just woke up from his coma thanks to some extreme science.");
		suspicion = suspicion - 1;	
	}
    
	// .............
	// #24: Knock him out

	void passageInit_24()
	{
		this.Passages["Knock him out"] = new TwinePassage("Knock him out", new string[]{  }, passageExecute_24);
	}

	IEnumerable<TwineOutput> passageExecute_24()
	{
		sociability = sociability - 1;
		yield return new TwineText(@"Aya decides that it's safer if he doesn't get out of there and start speaking and asking questions. She takes a heavy thing and hits him on the back of the head.//What to do with the ""body?""");	
	}
    
	// .............
	// #25: More talking

	void passageInit_25()
	{
		this.Passages["More talking"] = new TwinePassage("More talking", new string[]{  }, passageExecute_25);
	}

	IEnumerable<TwineOutput> passageExecute_25()
	{
		yield return new TwineText(@"Now they have to decide what to do, possibly together. Guy proposes his help because he's not too bad at solving problems.//What to do next?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Tell someone else about it.", @"Tell someone else about it.", @"Tell someone else about it.", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"Keep it your secret forever.", @"Keep it your secret forever.", @"Keep it your secret forever.", null, null);	
	}
    
	// .............
	// #26: Tell someone else about it.

	void passageInit_26()
	{
		this.Passages["Tell someone else about it."] = new TwinePassage("Tell someone else about it.", new string[]{  }, passageExecute_26);
	}

	IEnumerable<TwineOutput> passageExecute_26()
	{
		yield return new TwineText(@"They speak for a while, and decide to tell best friend about it.");
		if (metFriend > 0) { yield return new TwineText(@"/Next day, Aya calls her, explaining how the experiment went and that it worked and she now was in presence of the first human to ever be brought back to life.");} 
		if (metFriend < 0) { yield return new TwineText(@"/Aya calls her friend, and has to explain everything to her but in the end she gets to it. Friend has to come all the way to her house to see the death certificate with her own eyes to believe her, and finally does.");} 
		yield return new TwineText(@"///They think about what to do, and pool their ideas.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"End:Give everything to a charity and stop dealing about it", @"End:Give everything to a charity and stop dealing about it", @"End:Give everything to a charity and stop dealing about it", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"End:keep experimenting", @"End:keep experimenting", @"End:keep experimenting", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"Sell it to another company", @"Sell it to another company", @"Sell it to another company", null, null);	
	}
    
	// .............
	// #27: Keep it your secret forever.

	void passageInit_27()
	{
		this.Passages["Keep it your secret forever."] = new TwinePassage("Keep it your secret forever.", new string[]{  }, passageExecute_27);
	}

	IEnumerable<TwineOutput> passageExecute_27()
	{
		yield return new TwineText(@"Aya suggests that they shouldn't tell anyone about it and keep it to themselves. But what to do with it?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"End: Destroy the solution and all the notes.", @"End: Destroy the solution and all the notes.", @"End: Destroy the solution and all the notes.", null, null);
		yield return new TwineLink(@"End:Keep it for themselves, but use it for good reasons.", @"End:Keep it for themselves, but use it for good reasons.", @"End:Keep it for themselves, but use it for good reasons.", null, null);	
	}
    
	// .............
	// #28: End: Destroy the solution and all the notes.

	void passageInit_28()
	{
		this.Passages["End: Destroy the solution and all the notes."] = new TwinePassage("End: Destroy the solution and all the notes.", new string[]{  }, passageExecute_28);
	}

	IEnumerable<TwineOutput> passageExecute_28()
	{
		yield return new TwineText(@"They decide it's a bad thing to have that much power for two people, so they should destroy the solution.//With a bit of paperwork and talking to people, Aya manages to make the disparition of a corpse go unnoticed. Guy gets a change of identity, and starts working for some shady thing or another.//The end");	
	}
    
	// .............
	// #29: End:Keep it for themselves, but use it for good reasons.

	void passageInit_29()
	{
		this.Passages["End:Keep it for themselves, but use it for good reasons."] = new TwinePassage("End:Keep it for themselves, but use it for good reasons.", new string[]{  }, passageExecute_29);
	}

	IEnumerable<TwineOutput> passageExecute_29()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #30: The man is freaking out

	void passageInit_30()
	{
		this.Passages["The man is freaking out"] = new TwinePassage("The man is freaking out", new string[]{  }, passageExecute_30);
	}

	IEnumerable<TwineOutput> passageExecute_30()
	{
		yield return new TwineText(@"He's like HOLY SHIT WTF HAPPENED TO ME PLEASE LET ME OUT.//He's getting violent and threatening Aya.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Try to speak to him", @"Try to speak to him", @"Try to speak to him", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"Use the force", @"Use the force", @"Use the force", null, null);	
	}
    
	// .............
	// #31: Try to speak to him

	void passageInit_31()
	{
		this.Passages["Try to speak to him"] = new TwinePassage("Try to speak to him", new string[]{  }, passageExecute_31);
	}

	IEnumerable<TwineOutput> passageExecute_31()
	{
		sociability = sociability + 1;
		suspicion = suspicion - 1;
		yield return new TwineText(@"");
		yield return new TwineText(@"You get back a little and try to speak to him, tell him it's going to be ok, yadda yadda.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"More talking", @"More talking", @"More talking", null, null);	
	}
    
	// .............
	// #32: Use the force

	void passageInit_32()
	{
		this.Passages["Use the force"] = new TwinePassage("Use the force", new string[]{  }, passageExecute_32);
	}

	IEnumerable<TwineOutput> passageExecute_32()
	{
		morals = morals - 1;
		sociability = sociability - 1;
		suspicion = suspicion + 1;
		yield return new TwineText(@"");
		yield return new TwineText(@"She tries to knock him out. Considering he's bigger and stronger than her, that doesn't work much, so he pushes her down and run away. She tries to go after him but loses him quickly.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Go tell boss about it", @"Go tell boss about it", @"Go tell boss about it", null, null);	
	}
    
	// .............
	// #33: Go tell boss about it

	void passageInit_33()
	{
		this.Passages["Go tell boss about it"] = new TwinePassage("Go tell boss about it", new string[]{  }, passageExecute_33);
	}

	IEnumerable<TwineOutput> passageExecute_33()
	{
		morals = morals + 1;
		yield return new TwineText(@"");
		yield return new TwineText(@"Aya decides it's safer to go and tell her boss about it since there's a crazy naked man running around in the facility, which is probably not a good thing.//She has to explain the whole reviving thing, boss is amazed, and tells her to go home and not get out until he calls her.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Next day", @"Next day", @"Next day", null, null);	
	}
    
	// .............
	// #34: Next day

	void passageInit_34()
	{
		this.Passages["Next day"] = new TwinePassage("Next day", new string[]{  }, passageExecute_34);
	}

	IEnumerable<TwineOutput> passageExecute_34()
	{
		yield return new TwineText(@"Boss calls her and tell her to come as soon as she can.//When she's there, he tells her that the man was caught and locked inside the lab with guards, but that's not her problem anymore. He asks about what she did, and if it's reproducible.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"No", @"No", @"No", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes", @"Yes", @"Yes", null, null);	
	}
    
	// .............
	// #35: No

	void passageInit_35()
	{
		this.Passages["No"] = new TwinePassage("No", new string[]{  }, passageExecute_35);
	}

	IEnumerable<TwineOutput> passageExecute_35()
	{
		morals = morals + 1;
		yield return new TwineText(@"");
		yield return new TwineText(@"Aya doesn't want boss to put his hands on this so she refuses to do it.//Threatening happens.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes", @"Yes", @"Yes", null, null);	
	}
    
	// .............
	// #36: Yes

	void passageInit_36()
	{
		this.Passages["Yes"] = new TwinePassage("Yes", new string[]{  }, passageExecute_36);
	}

	IEnumerable<TwineOutput> passageExecute_36()
	{
		morals = morals - 1;
		yield return new TwineText(@"");
		yield return new TwineText(@"He then asks her to stay close and not tell anything to anyone.//Later in the night, he calls her and tell her that there is someone he wants her to bring back to life in particular, and takes her to the body.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Do it", @"Do it", @"Do it", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"Pretend it didn't work", @"Pretend it didn't work", @"Pretend it didn't work", null, null);	
	}
    
	// .............
	// #37: Do it

	void passageInit_37()
	{
		this.Passages["Do it"] = new TwinePassage("Do it", new string[]{  }, passageExecute_37);
	}

	IEnumerable<TwineOutput> passageExecute_37()
	{
		yield return new TwineText(@"She prepares more of the solution and inject it to the body. And tadam, it works!//Boss is happy because it was his wife, cue a very sentimental scene.//Boss tells Aya she'll get a so many % raise if she continues doing that, shares her recipe, and lead the whole thing.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Accept", @"Accept", @"Accept", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"Refuse", @"Refuse", @"Refuse", null, null);	
	}
    
	// .............
	// #38: Pretend it didn't work

	void passageInit_38()
	{
		this.Passages["Pretend it didn't work"] = new TwinePassage("Pretend it didn't work", new string[]{  }, passageExecute_38);
	}

	IEnumerable<TwineOutput> passageExecute_38()
	{
		yield return new TwineText(@"Boss is not happy. He sends her home and tells her not to tell anyone about it or else she will get problems.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Next day again", @"Next day again", @"Next day again", null, null);	
	}
    
	// .............
	// #39: Refuse

	void passageInit_39()
	{
		this.Passages["Refuse"] = new TwinePassage("Refuse", new string[]{  }, passageExecute_39);
	}

	IEnumerable<TwineOutput> passageExecute_39()
	{
		yield return new TwineText(@"Mild threatening happens. He tells Aya that she if she still chooses to refuse, there's going to be consequences.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Accept", @"Accept", @"Accept", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"Still refuse", @"Still refuse", @"Still refuse", null, null);	
	}
    
	// .............
	// #40: Accept

	void passageInit_40()
	{
		this.Passages["Accept"] = new TwinePassage("Accept", new string[]{  }, passageExecute_40);
	}

	IEnumerable<TwineOutput> passageExecute_40()
	{
		yield return new TwineText(@"She accepts.//In the next few days, everything is set up so she has a whole team for herself.");
		yield return new TwineText(@"");
		if (morals > 0) { 
		yield return new TwineLink(@"End:Do good", @"End:Do good", @"End:Do good", null, null);} 
		if (morals <= 0) { 
		yield return new TwineLink(@"End:Do bad", @"End:Do bad", @"End:Do bad", null, null);} 	
	}
    
	// .............
	// #41: End:Do good

	void passageInit_41()
	{
		this.Passages["End:Do good"] = new TwinePassage("End:Do good", new string[]{  }, passageExecute_41);
	}

	IEnumerable<TwineOutput> passageExecute_41()
	{
		yield return new TwineText(@"With all that power, Aya tries to do her best to help people.");	
	}
    
	// .............
	// #42: End:Do bad

	void passageInit_42()
	{
		this.Passages["End:Do bad"] = new TwinePassage("End:Do bad", new string[]{  }, passageExecute_42);
	}

	IEnumerable<TwineOutput> passageExecute_42()
	{
		yield return new TwineText(@"The call of money and power is strong, and Aya became rich selling her solution to multiple companies. It threw the world into chaos, because humanity wasn't ready for that. Being revived became a rich person thing, and the richest ones basically became immortal.//Congrats, you fucked up everything!");	
	}
    
	// .............
	// #43: Ask friend about that

	void passageInit_43()
	{
		this.Passages["Ask friend about that"] = new TwinePassage("Ask friend about that", new string[]{  }, passageExecute_43);
	}

	IEnumerable<TwineOutput> passageExecute_43()
	{
		yield return new TwineText(@"Aya goes to the new lab of her friend and ask her what the fuck is this all about.//Friend explains that boss came to her because Aya refused to work for him, and she accepted because she was given lots of money.//She adds that Aya isn't even needed anymore anyway, and that she's basically fired and she should get all her stuff from her lab.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Go get stuff", @"Go get stuff", @"Go get stuff", null, null);	
	}
    
	// .............
	// #44: Shit.

	void passageInit_44()
	{
		this.Passages["Shit."] = new TwinePassage("Shit.", new string[]{  }, passageExecute_44);
	}

	IEnumerable<TwineOutput> passageExecute_44()
	{
		yield return new TwineText(@"Friend is tied on a chair in the middle of the room.//Boss tells Aya that she has a choice. Either watch her friend get tortured, or cooperate. Now he doesn't want to work with her because he doesn't trust her, so he asks her to just give him the instructions.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Give the instructions", @"Give the instructions", @"Give the instructions", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"Refuse to say anything", @"Refuse to say anything", @"Refuse to say anything", null, null);	
	}
    
	// .............
	// #45: Next day again

	void passageInit_45()
	{
		this.Passages["Next day again"] = new TwinePassage("Next day again", new string[]{  }, passageExecute_45);
	}

	IEnumerable<TwineOutput> passageExecute_45()
	{
		yield return new TwineText(@"Aya gets home, but pass by the lab and grab any clue of what she was doing in order to hide it.");
		yield return new TwineText(@"");
		if (metFriend > 0) { yield return new TwineText(@"Next day, you learn that the person who Aya was supposed to revive is alive. Turns out boss asked her best friend for help, and she accepted. She feels like shit.");
		yield return new TwineLink(@"Ask friend about that", @"Ask friend about that", @"Ask friend about that", null, null);} 
		yield return new TwineText(@"");
		if (metFriend < 0) { yield return new TwineText(@"Next day, boss calls Aya and tell her to join him in a weird place. She accepts, not knowing what he wants. When she gets there, she is locked inside with him and a bunch of scary people.");
		yield return new TwineLink(@"Shit.", @"Shit.", @"Shit.", null, null);} 	
	}
    
	// .............
	// #46: Give the instructions

	void passageInit_46()
	{
		this.Passages["Give the instructions"] = new TwinePassage("Give the instructions", new string[]{  }, passageExecute_46);
	}

	IEnumerable<TwineOutput> passageExecute_46()
	{
		yield return new TwineText(@"Boss smiles, but does nothing to free friend. he tells Aya that he will keep her and he will let her go when he's sure that Aya isn't a danger to him anymore.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"End:Go home, defeated", @"End:Go home, defeated", @"End:Go home, defeated", null, null);	
	}
    
	// .............
	// #47: Refuse to say anything

	void passageInit_47()
	{
		this.Passages["Refuse to say anything"] = new TwinePassage("Refuse to say anything", new string[]{  }, passageExecute_47);
	}

	IEnumerable<TwineOutput> passageExecute_47()
	{
		yield return new TwineText(@"Aya refuses to give the solution because she doesn't trust boss. He's pissed, and waves to one of his men to start hitting friend.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Give the instructions", @"Give the instructions", @"Give the instructions", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"Still don't give in", @"Still don't give in", @"Still don't give in", null, null);	
	}
    
	// .............
	// #48: Still don't give in

	void passageInit_48()
	{
		this.Passages["Still don't give in"] = new TwinePassage("Still don't give in", new string[]{  }, passageExecute_48);
	}

	IEnumerable<TwineOutput> passageExecute_48()
	{
		yield return new TwineText(@"Friend is in bad shape. She starts begging her to just tell him.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Give the instructions", @"Give the instructions", @"Give the instructions", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"End:Don't do anything", @"End:Don't do anything", @"End:Don't do anything", null, null);	
	}
    
	// .............
	// #49: End:Don't do anything

	void passageInit_49()
	{
		this.Passages["End:Don't do anything"] = new TwinePassage("End:Don't do anything", new string[]{  }, passageExecute_49);
	}

	IEnumerable<TwineOutput> passageExecute_49()
	{
		yield return new TwineText(@"Aya explains that this is too dangerous and she can't do that no matter what. Friend stopped moving, and boss tells his men to stop.//DEUS EX MACHINA!!!!! The guy who was revived crashes in, beats up everyone including boss, unties friend, grabs Aya by the hand and runs out.//Aya is like WTF.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Go hide somewhere", @"Go hide somewhere", @"Go hide somewhere", null, null);	
	}
    
	// .............
	// #50: Go hide somewhere

	void passageInit_50()
	{
		this.Passages["Go hide somewhere"] = new TwinePassage("Go hide somewhere", new string[]{  }, passageExecute_50);
	}

	IEnumerable<TwineOutput> passageExecute_50()
	{
		yield return new TwineText(@"Aya asks the guy what the fuck he thinks he's doing.//He explains that the guards weren't strong enough to keep him in because he got some weird powers that made him stronger.//They quickly go back to the actual problem : friend is still unconscious, and in a bad shape. Guy scolds Aya because she shouldn't have let that happen.//At some point they see that nothing more can be done for her.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"End:Or does it?", @"End:Or does it?", @"End:Or does it?", null, null);	
	}
    
	// .............
	// #51: End:Go home, defeated

	void passageInit_51()
	{
		this.Passages["End:Go home, defeated"] = new TwinePassage("End:Go home, defeated", new string[]{  }, passageExecute_51);
	}

	IEnumerable<TwineOutput> passageExecute_51()
	{
		yield return new TwineText(@"Aya goes home. A few days later, she learns that friend is let out too. Meanwhile, Aya had given boss all her stuff about the experiments.//Basically same end than do bad but Aya is just miserable.");	
	}
    
	// .............
	// #52: End:Or does it?

	void passageInit_52()
	{
		this.Passages["End:Or does it?"] = new TwinePassage("End:Or does it?", new string[]{  }, passageExecute_52);
	}

	IEnumerable<TwineOutput> passageExecute_52()
	{
		yield return new TwineText(@"They remember why they are here in the first place : the solution. Guy goes quickly at Aya's place to grab everything they need while Aya sneaks in the lab to get all the stuff they need, then they revive friend.//Boss managed to frame them for some crime or another, so they have to stay on the run. Thankfully, they get in contact with the right kind of person, which give them access to chemicals and stuff to keep doing what they do. They end up being the founders of an underground group of super powerful people who do neither good nor bad, but live together, and protect each other.//Finish that one on Aya being killed in order to be brought back again.");	
	}
    
	// .............
	// #53: Still refuse

	void passageInit_53()
	{
		this.Passages["Still refuse"] = new TwinePassage("Still refuse", new string[]{  }, passageExecute_53);
	}

	IEnumerable<TwineOutput> passageExecute_53()
	{
		yield return new TwineText(@"Boss is not happy. However, his wife tells him that he should just let it go and don't care about it. The confusion gives Aya the time necessary to run away.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Run away", @"Run away", @"Run away", null, null);	
	}
    
	// .............
	// #54: Run away

	void passageInit_54()
	{
		this.Passages["Run away"] = new TwinePassage("Run away", new string[]{  }, passageExecute_54);
	}

	IEnumerable<TwineOutput> passageExecute_54()
	{
		yield return new TwineText(@"She has no idea what's going to happen to her, but she just runs to her home. She passes by the lab to make sure she doesn't leave any clue behind, and hides everything in her home.//Next day, she wonders what's going to happen to her. She turns on the tv and sees that she's wanted by the authorities because boss said she stole important secrets. She leaves as soon as she can, taking the most important part of her research, destroying the rest, and also taking a few necessary things.//She has no idea where to go though.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"End:Go hide in a random place", @"End:Go hide in a random place", @"End:Go hide in a random place", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"Risk going back to the lab to get the guy", @"Risk going back to the lab to get the guy", @"Risk going back to the lab to get the guy", null, null);	
	}
    
	// .............
	// #55: End:Go hide in a random place

	void passageInit_55()
	{
		this.Passages["End:Go hide in a random place"] = new TwinePassage("End:Go hide in a random place", new string[]{  }, passageExecute_55);
	}

	IEnumerable<TwineOutput> passageExecute_55()
	{
		yield return new TwineText(@"Apparently she does a pretty good job at hiding, because no one finds her, not even friend. At some point she ends up burning the rest of her research because she thinks no single human should have such power.");	
	}
    
	// .............
	// #56: Risk going back to the lab to get the guy

	void passageInit_56()
	{
		this.Passages["Risk going back to the lab to get the guy"] = new TwinePassage("Risk going back to the lab to get the guy", new string[]{  }, passageExecute_56);
	}

	IEnumerable<TwineOutput> passageExecute_56()
	{
		yield return new TwineText(@"She tries to go back to the lab to let guy free. She sees friend at some point, and ask her for help in that. They free him, and they run away together.");
		yield return new TwineText(@"");
		if (metFriend < 0) { yield return new TwineText(@"They explain everything to friend, who thinks it's crazy.");} 
		yield return new TwineText(@"");
		yield return new TwineLink(@"End: Together, take over the world", @"End: Together, take over the world", @"End: Together, take over the world", null, null);	
	}
    
	// .............
	// #57: End: Together, take over the world

	void passageInit_57()
	{
		this.Passages["End: Together, take over the world"] = new TwinePassage("End: Together, take over the world", new string[]{  }, passageExecute_57);
	}

	IEnumerable<TwineOutput> passageExecute_57()
	{
		yield return new TwineText(@"At some point during the chase, Aya is killed. Her body is carried by friend and guy, and they hide well enough to end up finding a way to revive her.//They live together for a while. At some point, they find out that people who were revived become a lot stronger, and almost immortal. They decide to kill friend and revive her too, and to lead a revolution.");	
	}
    
	// .............
	// #58: Go get stuff

	void passageInit_58()
	{
		this.Passages["Go get stuff"] = new TwinePassage("Go get stuff", new string[]{  }, passageExecute_58);
	}

	IEnumerable<TwineOutput> passageExecute_58()
	{
		yield return new TwineText(@"Aya goes to her lab, to grab everything. When she's about to leave, guy suddenly catches up with her and tell her that he managed to escape and she needs to help him.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I can't do anything", @"I can't do anything", @"I can't do anything", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"Sure, come with me", @"Sure, come with me", @"Sure, come with me", null, null);	
	}
    
	// .............
	// #59: I can't do anything

	void passageInit_59()
	{
		this.Passages["I can't do anything"] = new TwinePassage("I can't do anything", new string[]{  }, passageExecute_59);
	}

	IEnumerable<TwineOutput> passageExecute_59()
	{
		yield return new TwineText(@"Aya says there's nothing she can do and ask him to leave her alone, before going home.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"End:A while later", @"End:A while later", @"End:A while later", null, null);	
	}
    
	// .............
	// #60: Sure, come with me

	void passageInit_60()
	{
		this.Passages["Sure, come with me"] = new TwinePassage("Sure, come with me", new string[]{  }, passageExecute_60);
	}

	IEnumerable<TwineOutput> passageExecute_60()
	{
		yield return new TwineText(@"They run to Aya's house, and she hides him in it.//They think of what to do next but they don't have many ideas.//After a while, something happens. They see on tv that there's going to be a live demonstration of reviving someone soon, so they get an idea : go to the lab and sabotage the thing.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Just do it", @"Just do it", @"Just do it", null, null);	
	}
    
	// .............
	// #61: End:A while later

	void passageInit_61()
	{
		this.Passages["End:A while later"] = new TwinePassage("End:A while later", new string[]{  }, passageExecute_61);
	}

	IEnumerable<TwineOutput> passageExecute_61()
	{
		yield return new TwineText(@"Aya ended up finding a new job with less responsibilities, and managed to get her life back on track. She doesn't hear from her previous job again.//However, one day someone knocks at her door. When she opens, She sees guy for a few seconds before he shoots her in the chest and kill her instantly.//When she opens her eyes, she sees she's in a lab, tied to a table with thick metal cables. She knows she's been revived, but she sees that there's a lot more equipment than what she needed when she did it.//Friend shows up, and explains to her that there's a new step to the procedure, that will make her forget about everything and become fully loyal to her.");	
	}
    
	// .............
	// #62: Just do it

	void passageInit_62()
	{
		this.Passages["Just do it"] = new TwinePassage("Just do it", new string[]{  }, passageExecute_62);
	}

	IEnumerable<TwineOutput> passageExecute_62()
	{
		yield return new TwineText(@"They manage to sneak into the lab thanks to guy's new powers.//What to do now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"End:good sabotage idea", @"End:good sabotage idea", @"End:good sabotage idea", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"End:bad sabotage idea", @"End:bad sabotage idea", @"End:bad sabotage idea", null, null);	
	}
    
	// .............
	// #63: End:good sabotage idea

	void passageInit_63()
	{
		this.Passages["End:good sabotage idea"] = new TwinePassage("End:good sabotage idea", new string[]{  }, passageExecute_63);
	}

	IEnumerable<TwineOutput> passageExecute_63()
	{
		yield return new TwineText(@"They change the solution ever so slightly so it won't work anymore.//Next day, they see the thing live on tv. It fails miserably. The whole lab is discredited and loose all its funding, and isn't able to continue working on that particular project.");	
	}
    
	// .............
	// #64: End:bad sabotage idea

	void passageInit_64()
	{
		this.Passages["End:bad sabotage idea"] = new TwinePassage("End:bad sabotage idea", new string[]{  }, passageExecute_64);
	}

	IEnumerable<TwineOutput> passageExecute_64()
	{
		yield return new TwineText(@"They do something bad which triggers an alarm or whatever, and some guards come and arrest her (especially since they're ready to deal with guy because they knew he escaped).//They get arrested and judged and everything, too bad.");	
	}
    
	// .............
	// #65: End:Give everything to a charity and stop dealing about it

	void passageInit_65()
	{
		this.Passages["End:Give everything to a charity and stop dealing about it"] = new TwinePassage("End:Give everything to a charity and stop dealing about it", new string[]{  }, passageExecute_65);
	}

	IEnumerable<TwineOutput> passageExecute_65()
	{
		yield return new TwineText(@"Aya suggests it's better to give it to a charity because they'll be the ones who can do the best possible things with it.//Fast forward a few years, they manage to find her back and give her a nobel prize against her will because it helped a lot.");	
	}
    
	// .............
	// #66: End:keep experimenting

	void passageInit_66()
	{
		this.Passages["End:keep experimenting"] = new TwinePassage("End:keep experimenting", new string[]{  }, passageExecute_66);
	}

	IEnumerable<TwineOutput> passageExecute_66()
	{
		yield return new TwineText(@"Guy suggests that they keep watching him to see what happens, and then keep experimenting.//They see that guy is getting stronger and stronger, and seeing his vitals, probably immortal, so they freak out. They try to make something to get him back to normal, but given that they have way less resources considering that they can't work at the lab anymore, it fails, and then start of a zombie apocalypse except that the zombies are immortal.");	
	}
    
	// .............
	// #67: Sell it to another company

	void passageInit_67()
	{
		this.Passages["Sell it to another company"] = new TwinePassage("Sell it to another company", new string[]{  }, passageExecute_67);
	}

	IEnumerable<TwineOutput> passageExecute_67()
	{
		yield return new TwineText(@"Friend's idea is to sell it to another company so they can get a whole bunch of money and stop caring about anything. The other two are a bit reticent, but she lists companies with CEOs known for having decent morals. They end up selling it for way more money than they will ever need.//However, things go downhill because of how the company uses the thing, and the earth is dying at a faster rate because of too much people. A space program is made, but only the ones who were revived can survive the trip, and the treatment having been made super expensive, only a select few can do it.//The three of them end up having to put everything they own into being revived in order to have a chance to survive.");	
	}

}